FROM hub-image.eiot6.com/base/tdengine-builder:v0.0.2 AS builder


WORKDIR /td
RUN git clone https://github.com/quinniup/TDengine.git
 

# Compile Source
RUN mkdir -p TDengine/debug
WORKDIR /td/TDengine/debug
RUN cmake .. -DBUILD_TOOLS=true -DBUILD_CONTRIB=true -DBUILD_HTTP=false -DWEBSOCKET=true
RUN make


CMD [ "pwd" ]