apiVersion: v1
kind: Service
metadata:
  namespace: mid
  name: iottd
  labels:
    app: iottd
spec:
  ports:
    - name: tcp6030
      protocol: "TCP"
      port: 6030
    - name: tcp6041
      protocol: "TCP"
      port: 6041
  selector:
    app: iottd