
name: Docker BuildX-AMD64 and Push

on:
  push:
    tags:
      - "v3*"

env:
  APP_NAME: tdengine
  DOCKERHUB_REPO: hub-image.eiot6.com/base

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-20.04]
  
    steps:
        -   name: Set reusable strings
            id: strings
            shell: bash
            run: |
                echo ::set-output name=tag::${GITHUB_REF#refs/*/}
                echo ::set-output name=datetime::$(date +"%Y-%m-%d_%H-%M-%S")
  
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v1

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

        -   name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                registry: hub-image.eiot6.com
                username: ${{ secrets.CYFL_TENCENT_DOCKERHUB_USER }}
                password: ${{ secrets.CYFL_TENCENT_DOCKERHUB_TOKEN }}
                
        -   name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                platforms: |
                    linux/amd64
                push: true
                build-args: |
                    APP_NAME=${{ env.APP_NAME }}
                    APP_VERSION=${{ steps.strings.outputs.tag }}
                tags: |
                    ${{ env.DOCKERHUB_REPO }}/${{ env.APP_NAME }}-amd64:latest
                    ${{ env.DOCKERHUB_REPO }}/${{ env.APP_NAME }}-amd64:${{ steps.strings.outputs.tag }}
